<?php
use Drupal\Core\Database\Database;
use Drupal\Core\Link;
use Drupal\Core\Url;
use Drupal\Core\Entity;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\User\UserInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function orcid_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
    $current_url = Url::fromRoute('<current>', array(), array('absolute' => TRUE))->toString();
    $url = Url::fromRoute('orcid.oauth_redirect', array('destination' => $current_url));
    $link = Link::fromTextAndUrl(t('Connect your ORCID iD'), $url);

    //https://members.orcid.org/logos-web-graphics
    $button = array(
        '#markup' => '<button id="connect-orcid-button"><img id="orcid-id-logo" src="http://orcid.org/sites/default/files/images/orcid_24x24.png" width=\'24\' height=\'24\' alt="ORCID logo"/>>Create or Connect your ORCID iD</button>',
        '#type' => '#markup',
        '#allowed_tags' => ['button', 'img', 'a'],
    );
    $form['orcid'] = array(
        '#markup' => '<div><img src="http://orcid.org/sites/default/files/images/orcid_16x16.png">' . $link->toString() . '</div>',
        //'#markup' => render($button),
    );
    //$form['#attached']['library'][] = 'orcid/orcid';
}

/**
 * Implements hook_ENTITY_TYPE_view_alter() for user entities.
 *
 * This function adds a default alt tag to the user_picture field to maintain
 * accessibility.
 */
function orcid_user_view_alter(array &$build, UserInterface $account, EntityViewDisplayInterface $display) {
    $id = orcid_load_id($account);
    if ($display->id() == 'user.user.default') {
        if ($id) {
            //https://members.orcid.org/logos-web-graphics
            $uri = 'http://orcid.org/' . $id;
            $url = Url::fromUri($uri, array('absolute' => TRUE));
            $link = Link::fromTextAndUrl($uri, $url)->toString();
        } else {
            $current_url = Url::fromRoute('<current>', array(), array('absolute' => TRUE))->toString();
            $url = Url::fromRoute('orcid.oauth_redirect', array('destination' => $current_url));
            $link = Link::fromTextAndUrl(t('Connect your ORCID iD'), $url)->toString();
        }
        $build['orcid'] = array(
            '#type' => 'item',
            '#markup' => '<div><img src="http://orcid.org/sites/default/files/images/orcid_16x16.png">' . $link . '</div>',
            '#weight' => -50,
        );
    }
}

function orcid_load_id($account) {
    if ($account->id()) {
        $query = Database::getConnection()
            ->select('orcid', 'o')
            ->fields('o', array('orcid'))
            ->condition('uid', $account->id(), '=');
        $result = $query->execute();
        foreach ($result as $item) {
            return $item->orcid;
        }
    }
    return false;
}

function orcid_delete_user($account) {
    if ($account->id()) {
        $query = Database::getConnection()
            ->delete('orcid')
            ->condition('uid', $account->id(), '=')
            ->execute();
    }
}